import Navbar from "@/components/Navbar";
import type { Metadata } from "next";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="mb-56">
      <Navbar />
      {children}
    </div>
  );
}
